- .github/ISSUE_TEMPLATE/release.yml
- .github/workflows/ci.yml
- .github/workflows/enforce-linking-issues.yml
- .github/workflows/publish_android.yml
- .github/workflows/publish_jvm.yml
- .github/workflows/update-release-project.yml
- build.gradle.kts
- examples/build.gradle.kts
- zenoh-java/build.gradle.kts
- zenoh-java/src/jvmMain/kotlin/io/zenoh/Zenoh.kt
Syncing repo with zenoh-kotlin. 
- Enables automatic snaphshot publication (Closes #28 ) 
- Adds issue templates
- Adds `enforce-linking-issues.yml` and `update-release-proyect.yml` workflows for better project management.
- Patches issue where zenoh-jni wouldn't be loaded under windows.
> Syncing with zenoh kotlin repository.

- zenoh-java/src/commonMain/kotlin/io/zenoh/Session.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/jni/JNIPublisher.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/jni/JNIQuery.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/jni/JNIUtils.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/jni/callbacks/JNIGetCallback.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/jni/callbacks/JNIQueryableCallback.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/jni/callbacks/JNISubscriberCallback.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/publication/Delete.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/publication/Publisher.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/publication/Put.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/query/Get.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/query/Reply.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/queryable/Query.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/sample/Attachment.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/sample/Sample.kt
- zenoh-java/src/commonTest/kotlin/io/zenoh/UserAttachmentTest.kt
- zenoh-jni/src/publisher.rs
- zenoh-jni/src/put.rs
- zenoh-jni/src/query.rs
- zenoh-jni/src/reply.rs
- zenoh-jni/src/session.rs
- zenoh-jni/src/subscriber.rs
- zenoh-jni/src/utils.rs
- zenoh-jni/src/value.rs
User attachment for Java Bindings.
The API is expanded with the following calls:
* `publisher.put(...).with_attachment(attachment)`
* `publisher.write(...).with_attachment(attachment)`
* `publisher.delete(...).with_attachment(attachment)`
* `session.put(...).with_attachment(attachment)`
* `query.reply(...).with_attachment(attachment)`
* `session.get(...).with_attachment(attachment)`
The Sample class now has an optional Attachment field as well.
Closes #29
> feat(user_attachment): user attachment implementation

- rust-toolchain.toml
Upgrades rust toolchain from `1.72.0` to `1.74.0`, fixing the CI failure.
> fix(ci): Update rust toolchain

- zenoh-jni/src/query.rs
- zenoh-jni/src/reply.rs
- zenoh-jni/src/subscriber.rs
As title, after introducing the user attachment feature, a bug was introduced in which the associated bytes were not freed after use.
> Fix user attachment bytes not beeing freed.

- zenoh-jni/Cargo.lock
- zenoh-jni/Cargo.toml
Upgrades uhlc library version from 0.6.0 to 0.7.0, necessary to build Zenoh-JNI after the recent changes on Zenoh from [PR #860](https://github.com/eclipse-zenoh/zenoh/pull/860).
> issue(sync): upgrading uhlc dependency version to 0.7.0 + cargo update

- examples/src/main/java/io/zenoh/ZPub.java
- examples/src/main/java/io/zenoh/ZPubThr.java
- examples/src/main/java/io/zenoh/ZQueryable.java
- examples/src/main/java/io/zenoh/ZSub.java
- examples/src/main/java/io/zenoh/ZSubThr.java
These changes remove reading from stdin for all examples, and align their behaviors and outputs across projects.
This PR is part of an effort across currently active Zenoh projects. To maintain examples' implementations as close to each other as possible, any changes identified in other projects will be replicated in this PR. As such, **please do not merge these changes until all PRs are ready for merging**.
Related PRs:
- https://github.com/eclipse-zenoh/zenoh/pull/768
- https://github.com/eclipse-zenoh/zenoh-c/pull/255
- https://github.com/eclipse-zenoh/zenoh-cpp/pull/103
- https://github.com/eclipse-zenoh/zenoh-kotlin/pull/47
- https://github.com/eclipse-zenoh/zenoh-pico/pull/359
- https://github.com/eclipse-zenoh/zenoh-python/pull/150
> Align examples and remove reading from stdin

- .github/workflows/ci.yml
The CI workflow was failing because macos-latest now refers to macos-14 and the nttld/setup-ndk action doesn't support AArch64.
> fix: Use macos-13 instead of macos-14 runners in CI workflow

- ci/scripts/bump-and-tag.bash
[See this Release workflow run failure.](https://github.com/eclipse-zenoh/zenoh-kotlin/actions/runs/8803257959/job/24160917310)
> fix: Incorrect manifest path in cargo-check

- .github/workflows/release.yml
[Publishing workflows (JVM, Android, Dokka) aren't passed the release branch input.](https://github.com/eclipse-zenoh/zenoh-java/actions/runs/8895635099)
> fix: Missing `branch` input in publishing workflows

- .github/workflows/publish-jvm.yml
- rust-toolchain.toml
Similar to https://github.com/eclipse-zenoh/zenoh-kotlin/pull/86, this fixes how cargo installs cross and pins rustc to 1.72.0
> Update rustc version and how cross is installed via cargo

- .github/workflows/publish-jvm.yml
Attempt to fix https://github.com/eclipse-zenoh/zenoh-kotlin/issues/99
> fix: cargo-deb install from +stable and --locked

- .github/workflows/ci.yml
- .github/workflows/publish-android.yml
- .github/workflows/publish-jvm.yml
- README.md
- zenoh-java/build.gradle.kts
* Update gradle action (#103)
* Update gradle action to use setup-gradle
* chore: update setup-java action to v4
* chore: update gradle/wrapper-validation-action@v3
* Align CI with zenoh-kotlin
Brings the same changes done for zenoh-kotlin in
https://github.com/eclipse-zenoh/zenoh-kotlin/pull/133 to zenoh-java CI
* update README
* review comments
> Update dev/1.0.0 release workflow (#106)

- zenoh-java/src/commonMain/kotlin/io/zenoh/query/ConsolidationMode.kt
- zenoh-jni/src/utils.rs
Mainly motivated by the need to align default behavior of `get` with implementations in other bindings.
Sister PR:
> Add Query `Consolidation::Auto` to JNI and Java API

- .github/workflows/publish-jvm.yml
- zenoh-java/src/jvmMain/kotlin/io/zenoh/Target.kt
- zenoh-java/src/jvmMain/kotlin/io/zenoh/Zenoh.kt
Adding support for AARCH64 architectures on windows
> Aarch64 windows support

- .github/workflows/ci.yml
- .github/workflows/publish-android.yml
- .github/workflows/publish-jvm.yml
- .github/workflows/release.yml
- examples/build.gradle.kts
- zenoh-java/build.gradle.kts
Setting up remote publications to github packages and to maven central
> Publications alignment

- examples/build.gradle.kts
- examples/src/main/java/io/zenoh/ZQuerier.java
- zenoh-java/src/commonMain/kotlin/io/zenoh/Session.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/annotations/Annotations.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/jni/JNIQuerier.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/query/Querier.kt
- zenoh-java/src/jvmTest/java/io/zenoh/QuerierTest.java
- zenoh-jni/src/querier.rs
- zenoh-jni/src/session.rs
This PR adds the Querier feature, as well as a Querier example and a QuerierTest file.
> feat(querier): adding unstable Querier.

- examples/src/main/java/io/zenoh/ZGet.java
> Fix ZGet example

- zenoh-java/build.gradle.kts
This PR solves the issue of the CI workflows failing when attempting to build an Android package.
The reason for it failing is that it's not possible to target android while having mixed kotlin and java code.
However, the only java code we use is on the tests to validate the API. Since there are no android specific tests, we can safely disable the `withJava()` config when enabling android, solving the build problem.
> Disabling java tests when Android is enabled

- examples/src/main/java/io/zenoh/ZLiveliness.java
- examples/src/main/java/io/zenoh/ZPub.java
- examples/src/main/java/io/zenoh/ZPut.java
- examples/src/main/java/io/zenoh/ZQuerier.java
- examples/src/main/java/io/zenoh/ZQueryable.java
- zenoh-java/src/commonMain/kotlin/io/zenoh/Session.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/ext/ZDeserializer.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/pubsub/DeleteOptions.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/pubsub/Publisher.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/pubsub/PutOptions.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/query/Get.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/query/Querier.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/query/Query.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/query/Queryable.kt
- zenoh-java/src/commonMain/kotlin/io/zenoh/query/Reply.kt
- zenoh-java/src/jvmTest/java/io/zenoh/EncodingTest.java
On the Rust API we allow users to directly pass a payload as a string. This PR introduces that functionality to the Java API by providing function overloads that accept String parameters for payloads.
Example:
Instead of having to do like
```java
session.put(keyExpr, ZBytes.from("Example"));
```
now users can directly do
```java
session.put(keyExpr, "Example");
```
This applies to all the functions that expect some ZBytes parameter.
> String overloads as an alternative to ZBytes

- build.gradle.kts
- examples/README.md
- examples/build.gradle.kts
Adding tasks for creating executable jar's for the examples. The gradle task `buildExamples` will output fat jar's for each of the examples, which can be later run with:
```
java -jar <Example>.jar
```
Updating the examples README as well.
> Examples fat JARs

- .github/workflows/ci.yml
- .github/workflows/publish-android.yml
- .github/workflows/publish-dokka.yml
- .github/workflows/publish-jvm.yml
- .github/workflows/release.yml
- build.gradle.kts
- examples/build.gradle.kts
- gradle.properties
- zenoh-java/build.gradle.kts
Modifying gradle scripts and workflows for publishing packages into maven central (changes ported from zenoh-kotlin and addapted to zenoh-java).
> Maven publications

- .github/workflows/release.yml
During scheduled events, inputs are null, so we need to set this logic with contains() so we can:
- default to maven_publish=true, when workflow_dispatch is called
- allow maven_publish=true, when workflow_dispatch is called
- default to maven_publish=true, when running on a schedule
Should fix https://github.com/eclipse-zenoh/zenoh-java/actions/runs/13125305726
> fix: update release workflow for scheduled event

- zenoh-java/src/commonMain/kotlin/io/zenoh/Session.kt
This PR is equivalent to https://github.com/eclipse-zenoh/zenoh-kotlin/pull/442 on Kotlin.
> Session: save querier and publisher as weak refs

- .github/workflows/publish-jvm.yml
ubuntu-20.04 runners are being deprecated.
> chore: update ubuntu runners to ubuntu-24.04

- build.gradle.kts
As per https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/6270#note_4175210 we should use central.sonatype.org instead of oss.s.o
> ci: update sonatype.org url to use new domain

- build.gradle.kts
gradle-nexus/publish-plugin uses this new URL to transition to central. See https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/#configuration
> chore: update maven central url config

- .github/workflows/publish-jvm.yml
More specifically the windows-2019 got deprecated which causes the release workflow to be cancelled.
> ci: update workflow to use latest runners

- zenoh-jni/src/logger.rs
See https://discord.com/channels/914168414178779197/940584045287460885/1398224459558817854
> Fix panic when restarting the application
